services:
  main_dev_target:
    image: template-project-image1
    container_name: template-project1_v1.0
    build:
      context: ..
      dockerfile: dev/Dockerfile
    platform: linux/x86_64
    volumes:
      - ${PWD}/..:/home/${USER}/workspace
